### ISSUE TITLE
Urlspy regex fails on complex messages

### ISSUE THREAD

**Issue by poxip** [Xion/seejoo#22]
First, example:

``` irc
<me> https://google.pl/chrome
<seejoo> [] Przeglądarka Chrome
<me> https://google.pl/chrome dsds
nothing..
```

because parsed link is `https://google.pl/chrome dsds`, which is broken.

![](http://i.imgur.com/tSfmQNL.png)
http://goo.gl/8OPq5v

``` python
# Not entirely perfect regex but hey, it works :)
```

Nope :stuck_out_tongue_winking_eye:!

**Comment by Xion** [comment]
Problem was that final `.*` was capturing any following character. I have changed it to terminate at whitespace.
